services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      MONGO_URI: mongodb://mongo:27017/tradenote
      TRADENOTE_DATABASE: tradenote
      APP_ID: tradenote
      MASTER_KEY: changeme
      TRADENOTE_PORT: "8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - tradenote_db:/data/db
    environment:
      MONGO_INITDB_DATABASE: tradenote

volumes:
  tradenote_db:
